# window border
window.active.border.color: #bd93f9
window.inactive.border.color: #ff79c6

# ToggleKeybinds status indicator
window.active.indicator.toggled-keybind.color: #ff5555

# window titlebar background
window.active.title.bg.color: #bd93f9
window.inactive.title.bg.color: #ff79c6

window.active.label.text.color: #282a36
window.inactive.label.text.color: #4e1d32
window.label.text.justify: center

# window button hover overlay
window.button.hover.bg.color: #4d5066

# window buttons
window.active.button.unpressed.image.color: #282a36
window.inactive.button.unpressed.image.color: #282a36

# menu
menu.border.color: #282a36
menu.items.bg.color: #bd93f9
menu.items.text.color: #282a36
menu.items.active.bg.color: #ff79c6
menu.items.active.text.color: #4e1d32
menu.separator.color: #282a36
menu.title.bg.color: #bd93f9
menu.title.text.color: #282a36

# on screen display (window-cycle dialog)
osd.bg.color: #bd93f9
osd.border.color: #282a36
osd.label.text.color: #282a36
osd.window-switcher.preview.border.color: #6d728b
